// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovmaiszaashkttmozkxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bWFpc3phYXNoa3R0bW96a3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Mjc0NDMsImV4cCI6MjA3MjQwMzQ0M30.R0XWnC0MpRYfSuPOGO_oND6GmmKDu6b1nqpUJtv98C4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});